### ISSUE TITLE
1920x1080|  shape_overlay_img varibale not found 

### ISSUE THREAD

**Issue by retuparna-sebpo** [sebpo1/USCS_2832#1]
Generic_CPG_BottomFunnel_Neelie_1920x1080_MidEndCard
Generic_CPG_BottomFunnel_Neelie_1920x1080_BrandedCanvas_AdStudio_DynamicVideo.zip
Generic_CPG_BottomFunnel_Zoe_1920x1080_BrandedCanvas_AdStudio_DynamicVideo.zip

![image](https://github.com/sebpo1/USCS_2832/assets/106819920/ac88a4f1-6248-43fa-a9b3-74651e3974ae)

![image](https://github.com/sebpo1/USCS_2832/assets/106819920/eb26b58b-9cba-4c78-a4c8-1173654da32c)

**Comment by sharif-sebpo** [comment]
Please check the "default" version's variables to match the other version's variables as per "Sujan" vai. We'll notify the client about the missing variables.

**Comment by saudbinshahid** [comment]
![image](https://github.com/sebpo1/USCS_2832/assets/156332652/434b122f-9365-44c5-95bc-599c2d8d3bbd)
Missing for "Generic_CPG_BottomFunnel_Zoe_1920x1080_BrandedCanvas_AdStudio_DynamicVideo.zip" version

**Comment by sharif-sebpo** [comment]
Not applicable for "Generic_CPG_BottomFunnel_Zoe_1920x1080_BrandedCanvas_AdStudio_DynamicVideo.zip" this version

**Comment by saudbinshahid** [comment]
Closed as per developer comment.
