### ISSUE TITLE
1920x1080| Crave | BrandedCanvas | version name mismatch

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2832#2]
![image](https://github.com/sebpo1/USCS_2832/assets/142499806/d101a2f6-a885-4772-8697-be22776eb72d)

**Comment by sharif-sebpo** [comment]
Issues are fix

**Comment by saudbinshahid** [comment]
![image](https://github.com/sebpo1/USCS_2832/assets/156332652/825028bb-9d8e-43c2-a6fe-cd2f1a3f75b8)
