### ISSUE TITLE
1920x1080 | Generic_CPG_BottomFunnel_Soak_1920x1080_BottomThird_AdStudio_DynamicVideo.zip | product_img size mismatch

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2832#3]
![image](https://github.com/sebpo1/USCS_2832/assets/142499806/02da6fbf-fbe0-498f-a333-5279fd491272)

**Comment by sharif-sebpo** [comment]
Issues are fixed

**Comment by saudbinshahid** [comment]
![image](https://github.com/sebpo1/USCS_2832/assets/156332652/c1a6eadf-373e-4c2d-877f-5ecff2b957e5)
