### ISSUE TITLE
1920x1080| Subheadline_img  variable not found

### ISSUE THREAD

**Issue by retuparna-sebpo** [sebpo1/USCS_2832#4]
Generic_CPG_BottomFunnel_Neelie_1920x1080_BottomThird_
Generic_CPG_BottomFunnel_Crave_1920x1080_MidEndCard_

Generic_CPG_BottomFunnel_Neelie_1920x1080_BrandedCanvas_AdStudio_DynamicVideo.zip
Generic_CPG_BottomFunnel_Zoe_1920x1080_BrandedCanvas_AdStudio_DynamicVideo.zip

![image](https://github.com/sebpo1/USCS_2832/assets/106819920/19b3a0d2-a0a7-498d-b34d-5a3a8d5c6fea)
![image](https://github.com/sebpo1/USCS_2832/assets/106819920/c78ee836-8362-4c57-b209-ab6f4b5a8eac)

**Comment by sharif-sebpo** [comment]
We have updated the "subheadline_img" variable for "Generic_CPG_BottomFunnel_Neelie_1920x1080_BottomThird_" and for other creatives, please check the "default" version's variables to match the other version's variables as per "Sujan" vai. We'll notify the client about the missing variables.

**Comment by saudbinshahid** [comment]
![image](https://github.com/sebpo1/USCS_2832/assets/156332652/b688d35c-f1c2-4b53-bdd2-d3d779f3219d)
![image](https://github.com/sebpo1/USCS_2832/assets/156332652/0cc83069-d069-4b0b-9c5c-bcee66718363)

Missing for "Generic_CPG_BottomFunnel_Crave_1920x1080_MidEndCard_"

**Comment by sharif-sebpo** [comment]
Not applicable for "Generic_CPG_BottomFunnel_Crave_1920x1080_MidEndCard_" this version.

**Comment by saudbinshahid** [comment]
Closed as per developer comment.
